### PR TITLE
AstroBWT support

### PR DESCRIPTION
**Pull request by SChernykh**

### CODE REVIEW

**Comment by Spudz76** [comment]
Should this work with CUDA8 / Fermi cards?  None of mine seem to, but a Maxwell works.

**Comment by Spudz76** [comment]
Also seems to autosize about 5 times too large for VRAM.

**Comment by SChernykh** [comment]
It was only tested on Pascal/Turing cards.

**Comment by Spudz76** [comment]
Update, got it working on Fermi arch 21 CUDA 8.0GA2 not sure why it didn't work before (updated MSVC and latest dev branches were the only changes)

But still have memory error and then FPE error from Kepler arch 30 CUDA 10.2

oversized from autoconfig:
```
 * ABOUT        XMRig/5.10.1-dev-mo3 clang/11.0.0
 * LIBS         libuv/1.18.0 OpenSSL/1.1.1 hwloc/1.11.9
 * HUGE PAGES   supported
 * 1GB PAGES    disabled
 * CPU          Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (1) x64 AES
                L2:1.0 MB L3:6.0 MB 4C/8T NUMA:1
 * MEMORY       11.8/15.5 GB (76%)
 * DONATE       0%
 * ASSEMBLY     auto:intel
 * POOL #1      gulf.moneroocean.stream:20002 algo auto
 * COMMANDS     hashrate, pause, resume
 * CUDA         10.2/10.2/3.0.0
 * NVML         10.440.64/440.64 press e for health report
 * CUDA GPU     #0 01:00.0 Quadro K1100M 705/1400 MHz smx:2 arch:30 mem:1004/1999 MB
 * HTTP API     0.0.0.0:10084 
[2020-04-08 07:09:51.894] configuration saved to: "/opt/meta-miner-nv/config.json"
[2020-04-08 07:09:52.353]  net  use pool gulf.moneroocean.stream:20002 TLSv1.2 54.188.223.206
[2020-04-08 07:09:52.353]  net  fingerprint (SHA-256): "239daadd5c7d0ac097376c7871f787738826eef1c024729eff870e473b970855"
[2020-04-08 07:09:52.354]  net  new job from gulf.moneroocean.stream:20002 diff 710 algo astrobwt height 4644334
[2020-04-08 07:09:52.354]  nv   use profile  astrobwt  (1 thread) scratchpad 20480 KB
|  # | GPU |  BUS ID |    I |   T |   B | BF |  BS |  MEM | NAME
|  0 |   0 | 01:00.0 |  768 | 128 |   6 |  0 |   0 | 7140 | Quadro K1100M
[2020-04-08 07:09:52.512]  nv   READY threads 1/1 (158 ms)
[2020-04-08 07:09:52.521]  nv   thread #0 failed with error <astrobwt_prepare>:75 "out of memory"
[2020-04-08 07:09:54.266] Ctrl+C received, exiting
[2020-04-08 07:09:54.281]  nv   stopped (16 ms)
```

With that problem adjusted by hand and reduced to where it's not out of memory:
```
 * ABOUT        XMRig/5.10.1-dev-mo3 clang/11.0.0
 * LIBS         libuv/1.18.0 OpenSSL/1.1.1 hwloc/1.11.9
 * HUGE PAGES   supported
 * 1GB PAGES    disabled
 * CPU          Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (1) x64 AES
                L2:1.0 MB L3:6.0 MB 4C/8T NUMA:1
 * MEMORY       11.8/15.5 GB (76%)
 * DONATE       0%
 * ASSEMBLY     auto:intel
 * POOL #1      gulf.moneroocean.stream:20002 algo auto
 * COMMANDS     hashrate, pause, resume
 * CUDA         10.2/10.2/3.0.0
 * NVML         10.440.64/440.64 press e for health report
 * CUDA GPU     #0 01:00.0 Quadro K1100M 705/1400 MHz smx:2 arch:30 mem:1004/1999 MB
 * HTTP API     0.0.0.0:10084 
[2020-04-08 07:09:04.328]  net  use pool gulf.moneroocean.stream:20002 TLSv1.2 54.188.223.206
[2020-04-08 07:09:04.328]  net  fingerprint (SHA-256): "239daadd5c7d0ac097376c7871f787738826eef1c024729eff870e473b970855"
[2020-04-08 07:09:04.328]  net  new job from gulf.moneroocean.stream:20002 diff 717 algo astrobwt height 4644333
[2020-04-08 07:09:04.328]  nv   use profile  astrobwt  (1 thread) scratchpad 20480 KB
|  # | GPU |  BUS ID |    I |   T |   B | BF |  BS |  MEM | NAME
|  0 |   0 | 01:00.0 |   72 |  12 |   6 |  8 | 100 |  669 | Quadro K1100M
[2020-04-08 07:09:04.470]  nv   READY threads 1/1 (142 ms)
Floating point exception (core dumped)
```

**Pull request merged**
