### PR TITLE
CUDA for MacOS

### PR DESCRIPTION
**Pull request by Miner29974**
Hi

do it exist a plug-in for macOS?
If not is there a développer who can try do do it?

thank you

### CODE REVIEW

**Comment by Spudz76** [comment]
Nvidia dropped MacOS support as of CUDA Toolkit 10.2.

CUDA Toolkit 10.2 works on 10.13 High Sierra.  Unknown if it works on anything newer.

None of the devs here have Apple anything therefore the lack of full support.  But usually Apple does something that breaks things anyway, like deprecating OpenCL and not really wanting CUDA to work either (both in preference of everyone switching to Metal).

**Comment by Spudz76** [comment]
I have successfully compiled for MacOS High Sierra 10.13 with CUDA Toolkit 10.2 (the last version of OSX, and the last version of CUDA to support any MacOS).  It did not work out-of-the-box and took some changes, I will clean these up and submit as PR, even though it doesn't matter anymore, but in case someone wants to run old software to make it work.  Perhaps the CUDA Toolkit 10.2 can be installed on newer OS but nVidia claims 10.13 is the only supported one.  Probably the driver is broken in newer versions so having a plugin that can't talk to a GPU anyway would be a pointless success.

```
[100%] Linking CXX shared library libxmrig-cuda.dylib
[100%] Built target xmrig-cuda
```

**Comment by Miner29974** [comment]
Hello

Your job is great ! Do you think it will work with OS X Sierra and Cuda 6.xxx?

Thank you.

Envoyé de mon iPad

**Comment by Spudz76** [comment]
Minimum supported CUDA is 8.0 for any platform, and minimum GPU "capability level" (arch) of 2.0 (Fermi)

It should work with Sierra (10.12) with [CUDA Toolkit 9.0](https://developer.nvidia.com/cuda-90-download-archive?target_os=MacOSX&target_arch=x86_64&target_version=1012) for sure since it says it supports 10.12 directly.  Perhaps newer Toolkits still work but they all say 10.13.

**Comment by Spudz76** [comment]
Working build fixes in #104 

If you could test a build and then a run.  You may have to set the cuda->loader path in config.json to where the `libxmrig-cuda.dylib` is located.  `null` was trying to load OpenCL for some reason in my limited testing (with no GPU).

It should at least locate the GPU and possibly will even work.

**Comment by Spudz76** [comment]
Repaired the `loader: null` problem in main xmrig, pending PR.  Then copying the `libxmrig-cuda.dylib` along side xmrig executable and `null` setting as default will work, same as other platforms.

**Comment by Spudz76** [comment]
I see you are actually meaning to use 320M which is too old for mining. :(

**Comment by Miner29974** [comment]
Yes, it is for play with xmrig and m’y old MacBook and try to learn about mining.

I dont understrand where to found in github the file to put next xmrig.

Thank you
Regards.

Envoyé de mon iPad

**Review by SickZauer — APPROVED** [review]

**Pull request merged**
